import type { LegacyScanResult } from '../../types';

export type CacheUsageItem = {
  timestamp: string;
  prompt: string;
  cacheRead: number;
  cacheCreation: number;
  inputTokens: number;
};

export type TreemapNode = {
  name: string;
  originalName?: string;
  size?: number;
  tokens?: number;
  percentage?: number;
  color?: string;
  children?: TreemapNode[];
  cacheDetails?: CacheUsageItem[];
  claudeMdPreview?: string;
  status?: 'warning' | 'good' | 'info' | 'neutral';
  statusBadge?: string;
};

export const COLORS = {
  claudeMd: '#e74c3c',
  cacheCreation: '#f39c12',
  cacheRead: '#27ae60',
  userInput: '#3498db',
  output: '#9b59b6',
  section: '#1abc9c',
};

export const CATEGORY_INFO: Record<string, {
  friendlyName: string;
  icon: string;
  description: string;
  whatIsIt: string;
  status: 'warning' | 'good' | 'info' | 'neutral';
}> = {
  'CLAUDE.md': {
    friendlyName: '\u{1F4C4} Config File',
    icon: '\u{1F4C4}',
    description: 'AI instructions sent with every request',
    whatIsIt: 'CLAUDE.md is a set of instructions for the AI. It includes code style, rules, and conventions, and the entire content is sent with every request, incurring costs.',
    status: 'warning',
  },
  'Cache Creation': {
    friendlyName: '\u{1F195} New Cache',
    icon: '\u{1F195}',
    description: 'Cache to be reused in subsequent requests',
    whatIsIt: 'New context is being stored as cache. It costs now, but will be reused at a 90% discount from the next request onward.',
    status: 'info',
  },
  'Cache Read': {
    friendlyName: '\u267B\uFE0F Cached',
    icon: '\u267B\uFE0F',
    description: '90% cost savings!',
    whatIsIt: 'Content from previous conversations is being reused. Claude recognizes previously processed content and handles it quickly at a 90% discount.',
    status: 'good',
  },
  'User Input': {
    friendlyName: '\u{1F4AC} My Input',
    icon: '\u{1F4AC}',
    description: 'Your actual input',
    whatIsIt: 'Your actual prompts and conversation content. This is hard to reduce, but being concise and focused helps efficiency.',
    status: 'neutral',
  },
  'AI Output': {
    friendlyName: '\u{1F916} AI Response',
    icon: '\u{1F916}',
    description: 'AI-generated response',
    whatIsIt: 'Tokens generated by the AI. Output tokens cost 5x more than input, so request only what you need.',
    status: 'neutral',
  },
};

export const MODEL_PRICING = {
  'claude-sonnet-4-20250514': { name: 'Claude Sonnet 4', input: 3.0, output: 15.0, cacheRead: 0.3 },
  'claude-3-5-sonnet-20241022': { name: 'Claude 3.5 Sonnet', input: 3.0, output: 15.0, cacheRead: 0.3 },
  'claude-3-opus-20240229': { name: 'Claude 3 Opus', input: 15.0, output: 75.0, cacheRead: 1.5 },
  'claude-3-haiku-20240307': { name: 'Claude 3 Haiku', input: 0.25, output: 1.25, cacheRead: 0.03 },
  'claude-opus-4-20250514': { name: 'Claude Opus 4', input: 15.0, output: 75.0, cacheRead: 1.5 },
} as const;

export type ModelId = keyof typeof MODEL_PRICING;

export const DEMO_TREEMAP_DATA: TreemapNode[] = [
  { name: '\u{1F4C4} Config File', originalName: 'CLAUDE.md', size: 15234, tokens: 15234, percentage: 62.3, color: COLORS.claudeMd, status: 'warning', statusBadge: '\u26A0\uFE0F Top cost driver' },
  { name: '\u{1F195} New Cache', originalName: 'Cache Creation', size: 5234, tokens: 5234, percentage: 21.4, color: COLORS.cacheCreation, status: 'info', statusBadge: 'Reused next time' },
  { name: '\u267B\uFE0F Cached', originalName: 'Cache Read', size: 2891, tokens: 2891, percentage: 11.8, color: COLORS.cacheRead, status: 'good', statusBadge: '\u2705 90% savings!' },
  { name: '\u{1F4AC} My Input', originalName: 'User Input', size: 512, tokens: 512, percentage: 2.1, color: COLORS.userInput, status: 'neutral' },
  { name: '\u{1F916} AI Response', originalName: 'AI Output', size: 589, tokens: 589, percentage: 2.4, color: COLORS.output, status: 'neutral' },
];

export function buildTreemapData(data: LegacyScanResult): TreemapNode[] {
  const { breakdown } = data;
  const claudeMdPercentage = (breakdown.claudeMd.total / breakdown.total) * 100;

  return ([
    {
      name: CATEGORY_INFO['CLAUDE.md'].friendlyName,
      originalName: 'CLAUDE.md',
      size: breakdown.claudeMd.total,
      tokens: breakdown.claudeMd.total,
      percentage: claudeMdPercentage,
      color: COLORS.claudeMd,
      claudeMdPreview: data.cacheInfo?.claudeMdPreview?.slice(0, 200),
      status: (claudeMdPercentage > 40 ? 'warning' : 'neutral') as TreemapNode['status'],
      statusBadge: claudeMdPercentage > 40 ? '\u26A0\uFE0F Top cost driver' : undefined,
      children: data.claudeMdSections?.map((section, idx) => ({
        name: section.section,
        size: section.tokens,
        tokens: section.tokens,
        percentage: section.percentage,
        color: `hsl(${(idx * 30) % 360}, 70%, 50%)`,
      })),
    },
    {
      name: CATEGORY_INFO['Cache Creation'].friendlyName,
      originalName: 'Cache Creation',
      size: breakdown.cacheCreation,
      tokens: breakdown.cacheCreation,
      percentage: (breakdown.cacheCreation / breakdown.total) * 100,
      color: COLORS.cacheCreation,
      status: 'info',
      statusBadge: 'Reused next time',
      cacheDetails: data.cacheInfo?.recentCacheUsage?.filter(c => c.cacheCreation > 0),
    },
    {
      name: CATEGORY_INFO['Cache Read'].friendlyName,
      originalName: 'Cache Read',
      size: breakdown.cacheRead,
      tokens: breakdown.cacheRead,
      percentage: (breakdown.cacheRead / breakdown.total) * 100,
      color: COLORS.cacheRead,
      status: 'good',
      statusBadge: '\u2705 90% savings!',
      cacheDetails: data.cacheInfo?.recentCacheUsage?.filter(c => c.cacheRead > 0),
    },
    {
      name: CATEGORY_INFO['User Input'].friendlyName,
      originalName: 'User Input',
      size: breakdown.userInput,
      tokens: breakdown.userInput,
      percentage: (breakdown.userInput / breakdown.total) * 100,
      color: COLORS.userInput,
      status: 'neutral',
    },
    {
      name: CATEGORY_INFO['AI Output'].friendlyName,
      originalName: 'AI Output',
      size: breakdown.output,
      tokens: breakdown.output,
      percentage: (breakdown.output / breakdown.total) * 100,
      color: COLORS.output,
      status: 'neutral',
    },
  ] as TreemapNode[]).filter(node => (node.size || 0) > 0);
}

export function buildSilentTreemapData(data: LegacyScanResult): TreemapNode[] {
  const { breakdown } = data;

  return [
    {
      name: 'CLAUDE.md',
      size: breakdown.claudeMd.total,
      tokens: breakdown.claudeMd.total,
      percentage: (breakdown.claudeMd.total / breakdown.total) * 100,
      color: COLORS.claudeMd,
      claudeMdPreview: data.cacheInfo?.claudeMdPreview?.slice(0, 200),
      children: data.claudeMdSections?.map((section, idx) => ({
        name: section.section,
        size: section.tokens,
        tokens: section.tokens,
        percentage: section.percentage,
        color: `hsl(${(idx * 30) % 360}, 70%, 50%)`,
      })),
    },
    {
      name: 'Cache Creation',
      size: breakdown.cacheCreation,
      tokens: breakdown.cacheCreation,
      percentage: (breakdown.cacheCreation / breakdown.total) * 100,
      color: COLORS.cacheCreation,
      cacheDetails: data.cacheInfo?.recentCacheUsage?.filter(c => c.cacheCreation > 0),
    },
    {
      name: 'Cache Read',
      size: breakdown.cacheRead,
      tokens: breakdown.cacheRead,
      percentage: (breakdown.cacheRead / breakdown.total) * 100,
      color: COLORS.cacheRead,
      cacheDetails: data.cacheInfo?.recentCacheUsage?.filter(c => c.cacheRead > 0),
    },
    {
      name: 'User Input',
      size: breakdown.userInput,
      tokens: breakdown.userInput,
      percentage: (breakdown.userInput / breakdown.total) * 100,
      color: COLORS.userInput,
    },
    {
      name: 'AI Output',
      size: breakdown.output,
      tokens: breakdown.output,
      percentage: (breakdown.output / breakdown.total) * 100,
      color: COLORS.output,
    },
  ].filter(node => (node.size || 0) > 0);
}
